"use client";

import React, { createContext, useContext, useState, useEffect, ReactNode } from 'react';

// --- Types ---
type Language = 'en-US' | 'pt-BR' | 'es-ES';

// --- Translations ---
// Copied from original AppContext.tsx
const translations = {
    'en-US': {
        platform: 'Platform',
        resources: 'Resources',
        dashboard: 'Dashboard',
        wallets: 'Wallets',
        transactions: 'Transactions',
        insights: 'Insights',
        news: 'News',
        settings: 'Settings',
        signOut: 'Sign Out',
        welcomeBack: "Welcome back. Here's your portfolio overview.",
        addTransaction: 'Add Transaction',
        totalBalance: 'Total Balance',
        totalProfit: 'Total Profit',
        bestPerformer: 'Best Performer',
        activeWallets: 'Active Wallets',
        portfolioPerformance: 'Portfolio Performance',
        assetAllocation: 'Asset Allocation',
        topAsset: 'Top Asset',
        aiInsights: 'AI Insights',
        yourAssets: 'Your Assets',
        viewAll: 'View All',
        allWallets: 'All Wallets',
        asset: 'Asset',
        price: 'Price',
        balance: 'Balance',
        value: 'Value',
        avgPrice: 'Avg Price',
        pl: 'P/L',
        actions: 'Actions',
        last6Months: 'Last 6 Months',
        lastYear: 'Last Year',
        allTime: 'All Time',
        vsLastMonth: 'vs last month',
        buy: 'Buy',
        sell: 'Sell',
        transfer: 'Transfer',
        fromWallet: 'From Wallet',
        toWallet: 'To Wallet',
        notes: 'Observations',
        optional: 'Optional',
        quantity: 'Quantity',
        pricePerCoin: 'Price per Coin',
        date: 'Date',
        cancel: 'Cancel',
        walletsSubtitle: 'Manage your crypto portfolios and exchanges.',
        createWallet: 'Create Wallet',
        createNewWallet: 'Create New Wallet',
        syncedJustNow: 'Synced just now',
        walletName: 'Wallet Name',
        walletPlaceholder: 'e.g. My Ledger Nano',
        walletType: 'Wallet Type',
        type_LongTerm: 'Long-term',
        type_Trading: 'Trading',
        type_DeFi: 'DeFi',
        type_LongTermVault: 'Long-term Vault',
        type_TradingExchange: 'Trading / Exchange',
        type_DeFiYield: 'DeFi / Yield Farming',
        transactionsSubtitle: 'View and manage your transaction history.',
        exportCSV: 'Export CSV',
        searchTransactions: 'Search transactions...',
        filter: 'Filter',
        noTransactions: 'No transactions found. Add one to get started!',
        status: 'Status',
        completed: 'Completed',
        type: 'Type',
        totalValue: 'Total Value',
        amount: 'Amount',
        generateInsights: 'Generate AI Analysis',
        regenerate: 'Regenerate',
        insightsSubtitle: 'Automated analysis of risks, opportunities, and portfolio health.',
        loadingInsights: 'Analyzing your portfolio...',
        noHoldingsForInsights: 'Add assets to your portfolio to get AI insights.',
        newsSubtitle: 'Smart news feed grounded in your portfolio assets.',
        refreshNews: 'Refresh News',
        loadingNews: 'Searching global markets...',
        readMore: 'Read more',
        source: 'Source',
        divScore: 'Diversification Score',
        concRisk: 'Concentration Risk',
        perfAnalysis: 'Performance Analysis',
        rebalance: 'Rebalancing',
        temporal: 'Temporal Analysis',
        config: 'Configuration',
        markRead: 'Mark as Read',
        markApplied: 'Mark Applied',
        details: 'Details',
        all: 'All',
        new: 'New',
        landing_cta_login: 'Login',
        landing_cta_start: 'Get Started',
        landing_hero_title: 'Master Your Crypto Wealth',
        landing_hero_sub: 'The all-in-one platform for serious investors. Track, analyze, and optimize your portfolio across all wallets and exchanges.',
        landing_pain_title: 'Stop Trading in the Dark',
        landing_pain_1: 'Fragmented Assets',
        landing_pain_2: 'Spreadsheet Chaos',
        landing_pain_3: 'Missing Opportunities',
        landing_feat1_title: 'Unified Dashboard',
        landing_feat1_desc: 'Connect all your wallets and exchanges in one place. See your total net worth in real-time.',
        landing_feat2_title: 'Automated P&L',
        landing_feat2_desc: 'Forget manual spreadsheets. We automatically calculate your profit and loss across all trades.',
        landing_feat3_title: 'AI Analyst',
        landing_feat3_desc: 'Get personalized insights and actionable advice powered by advanced AI algorithms.',
        pricing_title: 'Simple Pricing',
        pricing_free_title: 'Starter',
        pricing_free_price: '$0',
        pricing_free_feat1: 'Up to 3 Wallets',
        pricing_free_feat2: 'Basic Analytics',
        pricing_free_feat3: 'Manual Sync',
        pricing_pro_title: 'Pro',
        pricing_pro_price: '$19',
        pricing_pro_cta: 'Start Free Trial',
        pricing_pro_feat1: 'Unlimited Wallets',
        pricing_pro_feat2: 'AI Insights',
        pricing_pro_feat3: 'Real-time Sync',
        pricing_pro_feat4: 'Priority Support',
        test_pedro_text: 'This app changed how I invest. The AI insights are scary good.',
        test_pedro_role: 'Crypto Investor',
        test_marina_text: 'Finally, I can see all my DeFi positions in one place. Game changer.',
        test_marina_role: 'DeFi Enthusiast',
        test_carlos_text: 'The best portfolio tracker I have ever used. Worth every penny.',
        test_carlos_role: 'Day Trader',
        landing_proof: 'Trusted by over 10,000 investors',
        landing_footer_text: 'Ready to take control?',
        landing_footer_rights: '© 2024 Atlas CryptoFolio. All rights reserved.',
    },
    'pt-BR': {
        platform: 'Plataforma',
        resources: 'Recursos',
        dashboard: 'Painel',
        wallets: 'Carteiras',
        transactions: 'Transações',
        insights: 'Insights',
        news: 'Notícias',
        settings: 'Configurações',
        signOut: 'Sair',
        welcomeBack: "Bem-vindo de volta. Aqui está o resumo do seu portfólio.",
        addTransaction: 'Nova Transação',
        totalBalance: 'Saldo Total',
        totalProfit: 'Lucro Total',
        bestPerformer: 'Melhor Ativo',
        activeWallets: 'Carteiras Ativas',
        portfolioPerformance: 'Performance do Portfólio',
        assetAllocation: 'Alocação de Ativos',
        topAsset: 'Principal Ativo',
        aiInsights: 'Insights de IA',
        yourAssets: 'Seus Ativos',
        viewAll: 'Ver Tudo',
        allWallets: 'Todas Carteiras',
        asset: 'Ativo',
        price: 'Preço',
        balance: 'Saldo',
        value: 'Valor',
        avgPrice: 'Preço Médio',
        pl: 'L/P',
        actions: 'Ações',
        last6Months: 'Últimos 6 Meses',
        lastYear: 'Último Ano',
        allTime: 'Todo o Período',
        vsLastMonth: 'vs mês anterior',
        buy: 'Comprar',
        sell: 'Vender',
        transfer: 'Transferir',
        fromWallet: 'Da Carteira',
        toWallet: 'Para Carteira',
        notes: 'Observações',
        optional: 'Opcional',
        quantity: 'Quantidade',
        pricePerCoin: 'Preço por Moeda',
        date: 'Data',
        cancel: 'Cancelar',
        walletsSubtitle: 'Gerencie seus portfólios e exchanges de cripto.',
        createWallet: 'Criar Carteira',
        createNewWallet: 'Criar Nova Carteira',
        syncedJustNow: 'Sincronizado agora',
        walletName: 'Nome da Carteira',
        walletPlaceholder: 'ex: Minha Ledger Nano',
        walletType: 'Tipo de Carteira',
        type_LongTerm: 'Longo Prazo',
        type_Trading: 'Trading',
        type_DeFi: 'DeFi',
        type_LongTermVault: 'Cofre de Longo Prazo',
        type_TradingExchange: 'Trading / Exchange',
        type_DeFiYield: 'DeFi / Yield Farming',
        transactionsSubtitle: 'Visualize e gerencie seu histórico de transações.',
        exportCSV: 'Exportar CSV',
        searchTransactions: 'Buscar transações...',
        filter: 'Filtrar',
        noTransactions: 'Nenhuma transação encontrada. Adicione uma para começar!',
        status: 'Status',
        completed: 'Concluído',
        type: 'Tipo',
        totalValue: 'Valor Total',
        amount: 'Montante',
        generateInsights: 'Gerar Análise IA',
        regenerate: 'Gerar Novamente',
        insightsSubtitle: 'Análise automatizada de riscos, oportunidades e saúde do portfólio.',
        loadingInsights: 'Analisando seu portfólio...',
        noHoldingsForInsights: 'Adicione ativos ao seu portfólio para obter insights da IA.',
        newsSubtitle: 'Feed de notícias inteligente baseado em seus ativos.',
        refreshNews: 'Atualizar Notícias',
        loadingNews: 'Buscando nos mercados globais...',
        readMore: 'Ler mais',
        source: 'Fonte',
        divScore: 'Score de Diversificação',
        concRisk: 'Risco de Concentração',
        perfAnalysis: 'Análise de Performance',
        rebalance: 'Rebalanceamento',
        temporal: 'Análise Temporal',
        config: 'Configuração',
        markRead: 'Marcar como Lido',
        markApplied: 'Marcar Aplicado',
        details: 'Detalhes',
        all: 'Todos',
        new: 'Novos',
        landing_cta_login: 'Entrar',
        landing_cta_start: 'Começar',
        landing_hero_title: 'Domine Sua Riqueza em Cripto',
        landing_hero_sub: 'A plataforma tudo-em-um para investidores sérios. Acompanhe, analise e otimize seu portfólio em todas as carteiras e exchanges.',
        landing_pain_title: 'Pare de Operar no Escuro',
        landing_pain_1: 'Ativos Fragmentados',
        landing_pain_2: 'Caos de Planilhas',
        landing_pain_3: 'Oportunidades Perdidas',
        landing_feat1_title: 'Painel Unificado',
        landing_feat1_desc: 'Conecte todas as suas carteiras e exchanges em um só lugar. Veja seu patrimônio total em tempo real.',
        landing_feat2_title: 'L/P Automatizado',
        landing_feat2_desc: 'Esqueça planilhas manuais. Calculamos automaticamente seu lucro e prejuízo em todas as operações.',
        landing_feat3_title: 'Analista IA',
        landing_feat3_desc: 'Obtenha insights personalizados e conselhos acionáveis com algoritmos avançados de IA.',
        pricing_title: 'Preços Simples',
        pricing_free_title: 'Inicial',
        pricing_free_price: 'R$0',
        pricing_free_feat1: 'Até 3 Carteiras',
        pricing_free_feat2: 'Análises Básicas',
        pricing_free_feat3: 'Sincronização Manual',
        pricing_pro_title: 'Pro',
        pricing_pro_price: 'R$89',
        pricing_pro_cta: 'Iniciar Teste Gratuito',
        pricing_pro_feat1: 'Carteiras Ilimitadas',
        pricing_pro_feat2: 'Insights de IA',
        pricing_pro_feat3: 'Sincronização em Tempo Real',
        pricing_pro_feat4: 'Suporte Prioritário',
        test_pedro_text: 'Este app mudou como eu invisto. Os insights de IA são incrivelmente precisos.',
        test_pedro_role: 'Investidor de Cripto',
        test_marina_text: 'Finalmente, posso ver todas as minhas posições DeFi em um lugar. Mudou o jogo.',
        test_marina_role: 'Entusiasta de DeFi',
        test_carlos_text: 'O melhor rastreador de portfólio que já usei. Vale cada centavo.',
        test_carlos_role: 'Day Trader',
        landing_proof: 'Confiado por mais de 10.000 investidores',
        landing_footer_text: 'Pronto para assumir o controle?',
        landing_footer_rights: '© 2024 Atlas CryptoFolio. Todos os direitos reservados.'
    },
    'es-ES': {
        platform: 'Plataforma',
        resources: 'Recursos',
        dashboard: 'Tablero',
        wallets: 'Billeteras',
        transactions: 'Transacciones',
        insights: 'Insights',
        news: 'Noticias',
        settings: 'Configuración',
        signOut: 'Cerrar Sesión',
        welcomeBack: "Bienvenido de nuevo. Aquí está el resumen de su cartera.",
        addTransaction: 'Nueva Transacción',
        totalBalance: 'Saldo Total',
        totalProfit: 'Beneficio Total',
        bestPerformer: 'Mejor Activo',
        activeWallets: 'Billeteras Activas',
        portfolioPerformance: 'Rendimiento de Cartera',
        assetAllocation: 'Asignación de Activos',
        topAsset: 'Activo Principal',
        aiInsights: 'Insights de IA',
        yourAssets: 'Sus Activos',
        viewAll: 'Ver Todo',
        allWallets: 'Todas Billeteras',
        asset: 'Activo',
        price: 'Precio',
        balance: 'Saldo',
        value: 'Valor',
        avgPrice: 'Precio Promedio',
        pl: 'G/P',
        actions: 'Acciones',
        last6Months: 'Últimos 6 Meses',
        lastYear: 'Último Año',
        allTime: 'Todo el Tiempo',
        vsLastMonth: 'vs mes anterior',
        buy: 'Comprar',
        sell: 'Vender',
        transfer: 'Transferir',
        fromWallet: 'De Billetera',
        toWallet: 'A Billetera',
        notes: 'Observaciones',
        optional: 'Opcional',
        quantity: 'Cantidad',
        pricePerCoin: 'Precio por Moneda',
        date: 'Fecha',
        cancel: 'Cancelar',
        walletsSubtitle: 'Administre sus carteras e intercambios de cifrado.',
        createWallet: 'Crear Billetera',
        createNewWallet: 'Crear Nueva Billetera',
        syncedJustNow: 'Sincronizado hace un momento',
        walletName: 'Nombre de la Billetera',
        walletPlaceholder: 'ej: Mi Ledger Nano',
        walletType: 'Tipo de Billetera',
        type_LongTerm: 'Largo Plazo',
        type_Trading: 'Trading',
        type_DeFi: 'DeFi',
        type_LongTermVault: 'Bóveda a Largo Plazo',
        type_TradingExchange: 'Comercio / Intercambio',
        type_DeFiYield: 'DeFi / Agricultura de Rendimiento',
        transactionsSubtitle: 'Ver y administrar su historial de transacciones.',
        exportCSV: 'Exportar CSV',
        searchTransactions: 'Buscar transacciones...',
        filter: 'Filtrar',
        noTransactions: 'No se encontraron transacciones. ¡Agrega una para comenzar!',
        status: 'Estado',
        completed: 'Completado',
        type: 'Tipo',
        totalValue: 'Valor Total',
        amount: 'Cantidad',
        generateInsights: 'Generar Análisis IA',
        regenerate: 'Regenerar',
        insightsSubtitle: 'Análisis automatizado de riesgos, oportunidades y salud de la cartera.',
        loadingInsights: 'Analizando su cartera...',
        noHoldingsForInsights: 'Agregue activos a su cartera para obtener insights de IA.',
        newsSubtitle: 'Noticias inteligentes basadas en sus activos.',
        refreshNews: 'Actualizar Noticias',
        loadingNews: 'Buscando en los mercados globais...',
        readMore: 'Leer más',
        source: 'Fuente',
        divScore: 'Puntaje de Diversificación',
        concRisk: 'Riesgo de Concentración',
        perfAnalysis: 'Análisis de Rendimiento',
        rebalance: 'Reequilibrio',
        temporal: 'Análisis Temporal',
        config: 'Configuración',
        markRead: 'Marcar como Leído',
        markApplied: 'Marcar Aplicado',
        details: 'Detalles',
        all: 'Todos',
        new: 'Nuevos',
        landing_cta_login: 'Iniciar Sesión',
        landing_cta_start: 'Comenzar',
        landing_hero_title: 'Domine Su Riqueza en Cripto',
        landing_hero_sub: 'La plataforma todo-en-uno para inversores serios. Rastree, analice y optimice su cartera en todas las billeteras e intercambios.',
        landing_pain_title: 'Deje de Operar a Ciegas',
        landing_pain_1: 'Activos Fragmentados',
        landing_pain_2: 'Caos de Hojas de Cálculo',
        landing_pain_3: 'Oportunidades Perdidas',
        landing_feat1_title: 'Panel Unificado',
        landing_feat1_desc: 'Conecte todas sus billeteras e intercambios en un solo lugar. Vea su patrimonio neto total en tiempo real.',
        landing_feat2_title: 'G/P Automatizado',
        landing_feat2_desc: 'Olvídese de las hojas de cálculo manuales. Calculamos automáticamente sus ganancias y pérdidas en todas las operaciones.',
        landing_feat3_title: 'Analista IA',
        landing_feat3_desc: 'Obtenga insights personalizados y consejos accionables con algoritmos avanzados de IA.',
        pricing_title: 'Precios Simples',
        pricing_free_title: 'Inicial',
        pricing_free_price: '$0',
        pricing_free_feat1: 'Hasta 3 Billeteras',
        pricing_free_feat2: 'Análisis Básico',
        pricing_free_feat3: 'Sincronización Manual',
        pricing_pro_title: 'Pro',
        pricing_pro_price: '$19',
        pricing_pro_cta: 'Comenzar Prueba Gratuita',
        pricing_pro_feat1: 'Billeteras Ilimitadas',
        pricing_pro_feat2: 'Insights de IA',
        pricing_pro_feat3: 'Sincronización en Tiempo Real',
        pricing_pro_feat4: 'Soporte Prioritario',
        test_pedro_text: 'Esta aplicación cambió mi forma de invertir. Los insights de IA son increíblemente precisos.',
        test_pedro_role: 'Inversor de Cripto',
        test_marina_text: 'Finalmente, puedo ver todas mis posiciones DeFi en un solo lugar. Cambió el juego.',
        test_marina_role: 'Entusiasta de DeFi',
        test_carlos_text: 'El mejor rastreador de cartera que he usado. Vale cada centavo.',
        test_carlos_role: 'Day Trader',
        landing_proof: 'Confiado por más de 10.000 inversores',
        landing_footer_text: '¿Listo para tomar el control?',
        landing_footer_rights: '© 2024 Atlas CryptoFolio. Todos los derechos reservados.'
    }
};

type TranslationKey = keyof typeof translations['en-US'];

interface LanguageContextType {
    language: Language;
    setLanguage: (lang: Language) => void;
    t: (key: TranslationKey) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
    // Language State
    const [language, setLanguage] = useState<Language>(() => {
        if (typeof window !== 'undefined') {
            const saved = localStorage.getItem('language');
            return (saved as Language) || 'en-US';
        }
        return 'en-US';
    });

    // Persist Language
    useEffect(() => {
        localStorage.setItem('language', language);
    }, [language]);

    const t = (key: TranslationKey): string => {
        const dict = translations[language] || translations['en-US'];
        return (dict as any)[key] || key;
    };

    return (
        <LanguageContext.Provider value={{ language, setLanguage, t }}>
            {children}
        </LanguageContext.Provider>
    );
};

export const useLanguage = () => {
    const context = useContext(LanguageContext);
    if (context === undefined) {
        throw new Error('useLanguage must be used within a LanguageProvider');
    }
    return context;
};
